# Generated by Django 2.1.5 on 2019-02-02 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
